version: '2'

services:
  db:
    #image: "postgres:9.5.2"
    image: tallyo_db
    volumes:
      - pgdatabase:/var/lib/postgresql/data
    networks:
      - back-tier
    environment:
      POSTGRES_USER: tuna_processor
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - "5432:5432"
  postgrest:
    #build:
    #  dockerfile: deploy/Dockerfile-postgrest
    #  context: .
    image: tallyo_postgrest
    restart: always
    networks:
      - back-tier
    ports:
      - "3000:3000"
    depends_on:
      - db
  amanda1:
    #build:
    #  dockerfile: deploy/Dockerfile-tallyo
    #  context: .
    image: tallyo_amanda1
#    command: sleep 10000000
    command: node app app_config_am1
    volumes:
#      - ./public/js/configs:/opt/tallyo/scanthis/public/js/configs
       - .:/opt/tallyo/scanthis
    ports:
      - "8000:8000"
    networks:
      - back-tier
    restart: always
    depends_on:
      - postgrest
  amanda2:
    image: tallyo_amanda1
    command: node app app_config_am2
    volumes:
#      - ./public/js/configs:/opt/tallyo/scanthis/public/js/configs
       - .:/opt/tallyo/scanthis
    ports:
      - "8001:8000"
    networks:
      - back-tier
    restart: always
    depends_on:
      - postgrest

  nginx:
    restart: always
    build: ./nginx/
    volumes_from:
      - amanda1
    networks:
      - back-tier
    ports:
      - "80:80"

volumes:
  pgdatabase:
    driver: local
  configs:
    driver: local

networks:
  back-tier:
    driver: bridge
