version: '2'

services:
  db:
    ports:
      - "5432:5432"

  amanda1:
    volumes:
      - ./migrations:/opt/tallyo/migrations
      - ./public:/opt/tallyo/public
    restart: never

  amanda2:
    volumes:
      - ./migrations:/opt/tallyo/migrations
      - ./public:/opt/tallyo/public
    restart: never