version: '2'

services:
  db:
    build:
      context: ./deploy/db
    image: tallyo_db
    volumes:
      - pgdatabase:/var/lib/postgresql/data
    networks:
      - back-tier
    environment:
      POSTGRES_USER: tuna_processor
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      DB_TIMEZONE: UTC
    restart: always

  postgrest:
    build:
      dockerfile: ./Dockerfile-postgrest
      context: ./deploy/postgrest
    image: tallyo_postgrest
    restart: always
    networks:
      - back-tier
  environment:
      DB_TIMEZONE: UTC
    ports:
      - "3000:3000"
    depends_on:
      - db

  amanda1:
    build:
      dockerfile: ./deploy/tallyo/Dockerfile
      context: .
    image: tallyo
    command: app app_config_am1
    volumes:
       - ./public:/opt/tallyo/public
    ports:
      - "8000:8000"
    environment:
      DB_RUNMIGRATIONS: 'true'
      DB_TIMEZONE: UTC
    networks:
      - back-tier
    restart: always
    depends_on:
      - postgrest

  amanda2:
    image: tallyo
    command: app app_config_am2
    volumes:
       - ./public:/opt/tallyo/public
    ports:
      - "8001:8000"
    environment:
      DB_RUNMIGRATIONS: 'false'
      DB_TIMEZONE: UTC
    networks:
      - back-tier
    restart: always
    depends_on:
      - postgrest
      - amanda1

  nginx:
    build:
      context: ./deploy/nginx
    image: tallyo_nginx
    restart: always
    volumes_from:
      - amanda1
    networks:
      - back-tier
    ports:
      - "80:80"
      - "81:81"

volumes:
  pgdatabase:
    driver: local

networks:
  back-tier:
    driver: bridge

