version: '2'

services:
  db:
    image: "postgres:9.5.2"
    volumes:
      - pgdatabase:/var/lib/postgresql/data
    networks:
      - back-tier
    environment:
      POSTGRES_USER: tuna_processor
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  postgrest:
    build:
      dockerfile: deploy/Dockerfile-postgrest
      context: .
    restart: always
    networks:
      - back-tier
    ports:
      - "3000:3000"
    depends_on:
      - db
  tallyo:
    build:
      dockerfile: deploy/Dockerfile-tallyo
      context: .
    command: node app app_config_hs
    volumes:
      - ./public/js/configs:/opt/tallyo/scanthis/public/js/configs
    ports:
      - "8000:8000"
    networks:
      - back-tier
    restart: always
    depends_on:
      - postgrest
volumes:
  pgdatabase:
    driver: local
  configs:
    driver: local

networks:
  back-tier:
    driver: bridge
