version: '2'

services:
  db:
    build:
      context: ./deploy/db
    image: tallyo_db
    volumes:
      - pgdatabase:/var/lib/postgresql/data
    networks:
      - back-tier
    environment:
      POSTGRES_USER: tuna_processor
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      TALLYO_TIMEZONE: UTC
    restart: always

  postgrest:
    build:
      dockerfile: ./Dockerfile-postgrest
      context: ./deploy/postgrest
    image: tallyo_postgrest
    restart: always
    networks:
      - back-tier
    environment:
      TALLYO_TIMEZONE: UTC
    ports:
      - "3000:3000"
    depends_on:
      - db

  amanda1:
    build:
      dockerfile: ./deploy/tallyo/Dockerfile
      context: .
    image: tallyo
    command: app app_config_am1
    ports:
      - "8000:8000"
    environment:
      DB_RUNMIGRATIONS: 'true'
      TALLYO_TIMEZONE: UTC
    networks:
      - back-tier
    restart: always
    depends_on:
      - postgrest

  amanda2:
    image: tallyo
    command: app app_config_am2
    ports:
      - "8001:8000"
    environment:
      DB_RUNMIGRATIONS: 'false'
      TALLYO_TIMEZONE: UTC
    networks:
      - back-tier
    restart: always
    depends_on:
      - postgrest
      - amanda1

volumes:
  pgdatabase:
    driver: local

networks:
  back-tier:
    driver: bridge

