version: '2'

services:

  backup:
    image: tallyo_db
    volumes:
       - backups:/bak
       - .:/code
    networks:
      - back-tier
    restart: always
    command: /code/deploy/backups/run_backups.sh

volumes:
  backups:
    driver: local
